### ISSUE TITLE
Lato Medium Missing (404) w/ http?

### ISSUE THREAD

**Issue by nemosupremo** [alfredxing/brick#113] opened 2015-05-13 22:02 UTC
Thanks for these fonts - however we started noticing the `Lato 500` throws a 404 errorwhen used with http (http://brick.a.ssl.fastly.net/fonts/lato/500.woff).

**Comment by alfredxing** [comment] 2015-05-14 04:43
Thanks for reporting this! The 404 was caused by the recent move to Collections--the `font` directory was renamed to `_fonts`, which didn't play well with our nginx config.

This should be fixed now. Extremely sorry for the inconvenience!

**Closed as completed** 2015-05-14 04:43 UTC
