### ISSUE TITLE
Catalogue link is 404

### ISSUE THREAD

**Issue by curiositry** [alfredxing/brick#63] opened 2014-06-19 04:54 UTC
http://brick.im/fonts/ goes to "There isn't a GitHub Page here."

**Comment by namanyayg** [comment] 2014-06-19 16:20
Same.

Edit: Seems like #62 is the cause. Oh well.

**Comment by alfredxing** [comment] 2014-06-19 16:50
Yeah, as @namanyayg mentioned, it's due to Jekyll being outdated on their side (#62). I've gotten an email response back from them, the rough response is posted in that issue.

Closing as duplicate.

**Closed as completed** 2014-06-19 16:50 UTC
Labels: duplicate
