### ISSUE TITLE
Font-weight is given an invalid value with italic fonts, causing wrong weights to be rendered

### ISSUE THREAD

**Issue by jpjoki** [alfredxing/brick#44] opened 2014-04-13 09:53 UTC
I noticed that the values given to font-weight in each @font-face rule are directly from the URL parameters. 

An example: http://brick.a.ssl.fastly.net/Linux+Libertine:400,400i

For the italic variant in that request, the font-weight is 400i. This is an invalid value, which means that the heaviest font loaded will be used for rendering all italics.

Looking at the following examples shows how this causes unwanted behavior. 

This page loads the fonts through a stylesheet link, like instructed:
http://www.film-o-holic.com/brick-example.html

It loads 400, 400i, 600,600i, 700, 700i for Linux Libertine and 400,400i,700,700i for Clear Sans. 

This pages loads the fonts through an inline CSS, where each @font-face has a correct font-weight value. Otherwise it's identical:
http://www.film-o-holic.com/brick-example-2.html

**Comment by iangeek** [comment] 2014-04-13 10:18
I'd spotted this symptom on Playfair Display also, but hadn't narrowed down the cause. Good spot @jpjoki

**Comment by alfredxing** [comment] 2014-04-13 18:04
Sorry about that, it's a bug resulting from the bug fix in b63830d947e4794d7541ee67194afa901e2dee5d.

Fixed in commit 597d2a8f05349e12b3fc47695883cc38afba29c6. I'm purging the cache now.

Thanks for the report!

**Closed as completed** 2014-04-13 18:04 UTC
